module.exports = {};
const animals = {
    aslan: {
          "name": "Aslan",
          "species": "Cat",
          "age": 7,
          "sex": "Male",
          "personality": "extraversion",
          "description": "Aslan is funny.",
          "image": "images/aslan.JPG",
        },
       sigfried: {
          "name": "Sigfried",
          "species": "Cat",
          "age": 2,
          "sex": "Male",
          "personality": "neuroticism",
          "description": "Sigried is funny.",
          "image": "images/sigfried.jpeg",
        },
        luna: {
          "name": "Luna",
          "species": "Dog",
          "age": 8,
          "sex": "Female",
          "personality": "openness",
          "description": "Luna is a playful and friendly dog.",
          "image": "images/luna.jpeg",
        },
        tessa: {
          "name": "Tessa",
          "species": "Dog",
          "age": 4,
          "sex": "Female",
          "personality": "",
          "description": "Tessa is a playful and friendly dog.",
          "image": "images/tessa.jpeg",
        },
        sally: {
          "name": "Sally",
          "species": "Cat",
          "age": 10,
          "sex": "Female",
          "personality": "",
          "description": "Sally is a playful and friendly cat.",
          "image": "images/sally.jpeg",
        },
        momo: {
          "name": "Momo",
          "species": "Cat",
          "age": 2,
          "sex": "Male",
          "personality": "conscientiousness",
          "description": "Momo is a playful and friendly cat.",
          "image": "images/momo.jpeg"
        },
        fluffy: {
          "name": "Fluffy",
          "species": "Cat",
          "age": 7,
          "sex": "Female",
          "personality": "",
          "description": "Fluffy is a playful and friendly cat.",
          "image": "images/fluffy.jpg",
        },
        max: {
          "name": "Max & Benito",
          "species": "Other",
          "age": 1,
          "sex": "Male",
          "personality": "",
          "description": "Max & Benito are playful and friendly rats.",
          "image": "images/max_benito.jpg",
        },
        enola: {
          "name": "Enola",
          "species": "Dog",
          "age": 1,
          "sex": "Female",
          "personality": "agreeableness",
          "description": "Enola is a playful and friendly dog.",
          "image": "images/enola.jpg",
        },
        frieda: {
          "name": "Frieda  & Vinnie",
          "species": "Other",
          "age": 1,
          "sex": "Female",
          "personality": "",
          "description": "Frieda & Vinnie are playful and friendly rats.",
          "image": "images/frieda_vinnie.jpg",
        },
        };
        module.exports = animals;