module.exports = {};
const animals = {
    aslan: {
          "name": "Aslan",
          "species": "Cat",
          "age": 7,
          "sex": "Male",
          "personality": "extraversion",
          "description": "Meet Aslan, the charming feline with a sunny disposition. This balcony-loving cat basks in the warmth of sunbeams and lets out an occasional cry to grab your attention. With a hearty appetite, especially when the moon is high, Aslan delights in indulging his taste buds. His affectionate nature extends to both humans and fellow pets, embracing the company of all. Aslan is a cuddle enthusiast, yet his daily routine includes playfully engaging in friendly battles. ",
          "image": "images/aslan.JPG",
        },
       siegfried: {
          "name": "Siegfried",
          "species": "Cat",
          "age": 2,
          "sex": "Male",
          "personality": "neuroticism",
          "description": "Siegfried is a whirlwind of feline energy, a mischievous ball of fur that never seems to run out of steam. With a perpetual twinkle in his eye, he embraces life with a zest that can only be described as both active and playful. From dawn till dusk, he's on a mission to explore every nook and cranny of his domain, effortlessly leaping from one surface to another, paws like a blur of lightning. But underneath his boundless enthusiasm lies a touch of craziness that adds an unpredictable charm to his character. Whether he's engaging in gravity-defying acrobatics or chasing imaginary creatures with an intensity that defies reason, Siegfried's antics never fail to leave onlookers both entertained and bewildered. He's the embodiment of a spirited feline, a captivating whirlwind of activity and eccentricity that keeps everyone on their toes.",
          "image": "images/sigfried.jpeg",
        },
        luna: {
          "name": "Luna",
          "species": "Dog",
          "age": 8,
          "sex": "Female",
          "personality": "openness",
          "description": "Luna, the delightful poodle, is the epitome of a canine companion who adores humans with every fiber of her being. Her warm and affectionate nature makes her the perfect addition to any family. From the moment she wakes up, Luna's tail wags with uncontainable joy, eagerly seeking out her human companions for hugs, cuddles, and endless playtime. Her eyes sparkle with an unwavering love and loyalty, always striving to please and bring happiness to those around her. Luna effortlessly adapts to the dynamics of the household, forming strong bonds with each family member and becoming a cherished confidant and friend. Whether it's joining in on adventures, providing comforting snuggles, or simply showering everyone with an abundance of love, Luna's presence enriches the lives of her loved ones, making her the quintessential embodiment of the perfect family dog.",
          "image": "images/luna.jpeg",
        },
        tessa: {
          "name": "Tessa",
          "species": "Dog",
          "age": 4,
          "sex": "Female",
          "personality": "",
          "description": "Tessa, the pint-sized bundle of energy, is a small dog with a larger-than-life personality. Despite her tiny stature, she possesses an insatiable drive for activity, always eager to explore the world around her. From sunrise to sunset, Tessa zooms around with a contagious enthusiasm, her tiny paws scampering tirelessly. But beneath her ceaseless energy lies a heart filled with affection and an undeniable love for cuddles. When her adventures wind down, Tessa eagerly seeks the warm embrace of her human companions, curling up in their laps or snuggling against their chests. With every gentle touch and tender stroke, her tail wags with contentment, and her eyes sparkle with pure adoration. Tessa is the embodiment of the perfect balance between boundless activity and unwavering affection, making her an irresistible companion for those who appreciate a furry friend that can keep up with their active lifestyle while also providing endless cuddles and warmth.",
          "image": "images/tessa.jpeg",
        },
        sally: {
          "name": "Sally",
          "species": "Cat",
          "age": 10,
          "sex": "Female",
          "personality": "",
          "description": "Sally, the wise and gentle soul, is an elderly cat who appreciates the beauty of solitude. With a calm demeanor and a touch of grace, she values her alone time, finding solace in quiet corners and sunlit spots where she can bask in the tranquility of her surroundings. Sally's independent nature is evident in her deliberate movements and wise, observant eyes. However, despite her love for solitude, she possesses a soft spot for occasional cuddles. In those tender moments, when the world quiets down and a familiar touch reaches out, Sally reveals her softer side. Nestling into the warm embrace of her human companion, she purrs with contentment, appreciating the comfort and connection that cuddling brings. Sally exemplifies the balance between independence and the need for affection, reminding us that even the most introverted souls can find joy in the gentle embrace of a caring touch.",
          "image": "images/sally.jpeg",
        },
        momo: {
          "name": "Momo",
          "species": "Cat",
          "age": 2,
          "sex": "Male",
          "personality": "conscientiousness",
          "description": "Momo, the curious feline explorer, finds sheer delight in the world beyond the confines of four walls. With an insatiable thirst for adventure, he yearns to be outside, immersing himself in the sights, sounds, and scents of his surroundings. Perched on windowsills or lounging on the patio, Momo becomes a vigilant observer, his eyes fixed intently on the ever-changing landscape. His ears twitch at the rustling of leaves and the chirping of birds, his whiskers tingle with each passing breeze. Momo's fascination with the outside world is a testament to his innate curiosity and his profound connection with nature. Whether he's perched on a tree branch, soaking up the warmth of the sun, or hiding in the bushes, plotting his next escapade, Momo's love for being outdoors fuels his adventurous spirit and reminds us of the innate connection between feline grace and the vast wonders of the natural world.",
          "image": "images/momo.jpeg"
        },
        fluffy: {
          "name": "Fluffy",
          "species": "Cat",
          "age": 11,
          "sex": "Female",
          "personality": "",
          "description": "Fluffy, the gentle elder stateswoman of the feline realm, embodies a quiet and introspective nature. With a demure presence and a delicate grace, she navigates the world with cautious steps and watchful eyes. Initially reserved and shy, Fluffy requires patience and understanding to build trust with new humans in her life. Like a delicate flower unfurling its petals, Fluffy takes her time to open up, gradually revealing her tender and affectionate heart. Once she feels safe and secure, she bestows upon her chosen human companions a love that knows no bounds. With gentle nudges and soft purrs, Fluffy seeks solace in the warmth of their presence, cherishing the bonds she has formed. Her love, though quiet, is profound, and those fortunate enough to earn her trust are rewarded with a glimpse into the depths of her gentle soul. Fluffy serves as a poignant reminder that true love often requires patience, understanding, and a willingness to allow others the time and space they need to bloom.",
          "image": "images/fluffy.jpg",
        },
        max: {
          "name": "Max & Benito",
          "species": "Other",
          "age": 1,
          "sex": "Male",
          "personality": "",
          "description": "Max and Benito, two inseparable brothers of the rodent kingdom, share a bond that transcends mere siblinghood. With their sleek fur and mischievous eyes, they navigate the world as a dynamic duo, exploring every nook and cranny with an insatiable curiosity. Together, they face adventures and challenges, their tails intertwined in a constant display of unity. Max, the bolder of the two, fearlessly leads the way, while Benito, the more cautious and thoughtful brother, provides a steady presence and clever solutions to any obstacles they encounter. Whether they're scurrying through tunnels or nibbling on tasty treats, their synchronized movements and shared experiences forge an unbreakable bond. Their chatter-filled conversations and playful wrestling matches exemplify the joyous camaraderie between them. Max and Benito are a testament to the unshakeable bond of brotherhood, reminding us that with a companion by our side, even the smallest creatures can conquer the world together.",
          "image": "images/max_benito.jpg",
        },
        enola: {
          "name": "Enola",
          "species": "Dog",
          "age": 1,
          "sex": "Female",
          "personality": "agreeableness",
          "description": "Enola, the spirited young pup, is a delightful whirlwind of mischief and adventure. With an insatiable curiosity and an appetite for exploration, she approaches life with boundless enthusiasm. Enola's mischievous nature knows no bounds, as she fearlessly embarks on expeditions to investigate every nook and cranny. However, her misadventures extend beyond mere curiosity—Enola has a penchant for consuming anything and everything in her path. From socks to shoes, and even the occasional household item, her appetite knows no limits. Despite the chaos she occasionally leaves in her wake, her playful antics and unabashed joy bring a smile to those around her. Enola's insatiable hunger for both discovery and the occasional inedible object serve as a constant reminder to her loved ones to keep a watchful eye and provide plenty of chew toys to keep her entertained. With a mischievous twinkle in her eyes and a heart full of endless energy, Enola reminds us that sometimes, it's the most rambunctious and unpredictable companions who bring the greatest joy into our lives.",
          "image": "images/enola.jpg",
        },
        frieda: {
          "name": "Frieda  & Vinnie",
          "species": "Other",
          "age": 1,
          "sex": "Female",
          "personality": "",
          "description": "Frieda and Vinnie, two inseparable sisters of the rat kingdom, share a bond that transcends the ordinary. With their sleek fur and bright, intelligent eyes, they navigate the world as a dynamic duo, united by an unbreakable sisterly love. Side by side, they explore their surroundings with unwavering curiosity, fearlessly venturing into new territories. Frieda, the adventurous spirit, fearlessly leads the way, while Vinnie, the gentle and intuitive sister, provides a calming presence and thoughtful guidance. Together, they engage in playful mischief and engage in intricate grooming rituals, their synchronized movements and rhythmic chatter displaying a profound understanding and deep connection. Through good times and challenging moments, Frieda and Vinnie are there for each other, offering comfort and companionship. Their sisterly bond serves as a powerful reminder that love and support from a cherished sibling can bring joy and strength, even in the smallest of creatures.",
          "image": "images/frieda_vinnie.jpg",
        },
        };
module.exports = animals;